<?php
return array(
	'title'            => esc_html__( 'Social Sharing', 'pgs-core' ),
	'id'               => 'social_sharing_settings',
	'desc'             => esc_html__( 'Enable/disable sharing functionality.', 'pgs-core' ),
	'customizer_width' => '400px',
	'icon'             => 'fa fa-share-alt',
	'fields'           => array(
		array(
			'id'       => 'facebook_share',
			'type'     => 'switch',
			'title'    => esc_html__( 'Facebook Share', 'pgs-core' ),
			'subtitle' => esc_html__( 'You can share post with Facebook.', 'pgs-core' ),
			'default'  => true,
		),
		array(
			'id'       => 'twitter_share',
			'type'     => 'switch',
			'title'    => esc_html__( 'Twitter Share', 'pgs-core' ),
			'subtitle' => esc_html__( 'You can share post with Twitter', 'pgs-core' ),
			'default'  => true,
		),
		array(
			'id'       => 'linkedin_share',
			'type'     => 'switch',
			'title'    => esc_html__( 'Linkedin Share', 'pgs-core' ),
			'subtitle' => esc_html__( 'You can share post with Linkedin', 'pgs-core' ),
			'default'  => true,
		),
		array(
			'id'       => 'pinterest_share',
			'type'     => 'switch',
			'title'    => esc_html__( 'Pinterest Share', 'pgs-core' ),
			'subtitle' => esc_html__( 'You can share post with Pinterest', 'pgs-core' ),
			'default'  => true,
		),
		array(
			'id'       => 'googlebookmarks_share',
			'type'     => 'switch',
			'title'    => esc_html__( 'GoogleBookmarks Share', 'pgs-core' ),
			'subtitle' => esc_html__( 'You can share post with GoogleBookmarks.', 'pgs-core' ),
			'default'  => false,
		),
		array(
			'id'       => 'reddit_share',
			'type'     => 'switch',
			'title'    => esc_html__( 'Reddit Share', 'pgs-core' ),
			'subtitle' => esc_html__( 'You can share post with Reddit.', 'pgs-core' ),
			'default'  => false,
		),
		array(
			'id'       => 'tumblr_share',
			'type'     => 'switch',
			'title'    => esc_html__( 'Tumblr Share', 'pgs-core' ),
			'subtitle' => esc_html__( 'You can share post with Tumblr.', 'pgs-core' ),
			'default'  => false,
		),
		array(
			'id'       => 'stumbleupon_share',
			'type'     => 'switch',
			'title'    => esc_html__( 'StumbleUpon Share', 'pgs-core' ),
			'subtitle' => esc_html__( 'You can share post with StumbleUpon.', 'pgs-core' ),
			'default'  => false,
		),
		array(
			'id'       => 'digg_share',
			'type'     => 'switch',
			'title'    => esc_html__( 'Digg Share', 'pgs-core' ),
			'subtitle' => esc_html__( 'You can share post with Digg.', 'pgs-core' ),
			'default'  => false,
		),
		array(
			'id'       => 'vk_share',
			'type'     => 'switch',
			'title'    => esc_html__( 'VK Share', 'pgs-core' ),
			'subtitle' => esc_html__( 'You can share post with VK.', 'pgs-core' ),
			'default'  => false,
		),
		array(
			'id'       => 'xing_share',
			'type'     => 'switch',
			'title'    => esc_html__( 'XING Share', 'pgs-core' ),
			'subtitle' => esc_html__( 'You can share post with XING.', 'pgs-core' ),
			'default'  => false,
		),
		array(
			'id'       => 'skype_share',
			'type'     => 'switch',
			'title'    => esc_html__( 'Skype Share', 'pgs-core' ),
			'subtitle' => esc_html__( 'You can share post with Skype.', 'pgs-core' ),
			'default'  => false,
		),
	),
);
